# Generated by Django 4.2.5 on 2023-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_distributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(choices=[('5', '5 Kgs'), ('50', '50 Kgs'), ('10', '10 Kgs'), ('20', '20 Kgs'), ('70', '70 Kgs')], default=5, max_length=2),
        ),
    ]
