# Generated by Django 4.2.5 on 2023-10-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_distributors_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributors",
            name="slug",
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
