# Generated by Django 4.2.5 on 2023-10-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_distributors_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Subscriber",
        ),
    ]
