# Generated by Django 4.2.5 on 2023-11-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_subscription_delete_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributors",
            name="contacts",
            field=models.CharField(max_length=12),
        ),
    ]
