# Generated by Django 4.2.5 on 2023-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_distributors_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("customer_name", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("additional_notes", models.TextField(blank=True)),
            ],
        ),
    ]
