# Generated by Django 4.2.5 on 2023-11-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "Contact Us"},
        ),
        migrations.AlterModelOptions(
            name="distributors",
            options={"verbose_name_plural": "Distributors"},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name_plural": "Subscriptions"},
        ),
        migrations.AddField(
            model_name="distributors",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
