# Generated by Django 4.2.5 on 2023-12-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_contactus_options_alter_distributors_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributors',
            name='tag',
        ),
    ]
