# Generated by Django 4.2.5 on 2023-09-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
