# Generated by Django 4.2.5 on 2023-09-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_braintree_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='pickup_point',
        ),
    ]
